import { useState } from "react";
import { Box, Typography, Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ProjectCard from "../../components/ProjectCard";

const projects = [
  {
    id: 1,
    title: "Salut!",
    body: "Bootstrap Carousel Example",
    imageUrl: "/../public/assets/bg2.jpg",
    docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
  },
  {
    id: 2,
    title: "Ranker",
    body: "Bootstrap Carousel Example",
    imageUrl: "/../public/assets/bg.jpg",
    docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
  },
  {
    id: 3,
    title: "Scheduler",
    body: "Bootstrap Carousel Example",
    imageUrl: "/../public/assets/bg2.jpg",
    docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
  },
  {
    id: 4,
    title: "Jungle",
    body: "Bootstrap Carousel Example",
    imageUrl: "/../public/assets/bg.jpg",
    docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
  },
  {
    id: 5,
    title: "Tiny App",
    body: "Bootstrap Carousel Example",
    imageUrl: "/../public/assets/bg.jpg",
    docs: "https://getbootstrap.com/docs/4.0/components/carousel/",
  },
];

const Projects = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          zIndex: -1,
          position: "fixed",
          width: "100vw",
          height: "100vh",
        }}
      >
        <Image
          src="/../public/assets/bg2.jpg"
          alt="background"
          layout="fill"
          objectFit="cover"
        />
      </div>
      <Box
        sx={{
          width: "100vw",
          p: 10,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Box
          sx={{
            color: "#798777",

            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Typography sx={{ fontSize: 45 }}>Projects</Typography>
        </Box>
        <Box
          sx={{
            textAlign: "center",
            m: 4,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {projects.map((item) => {
            return (
              <ProjectCard
                key={item.id}
                imageUrl={item.imageUrl}
                title={item.title}
                body={item.body}
              />
            );
          })}
        </Box>
      </Box>
    </>
  );
};

export default Projects;
