import Head from "next/head";
import BootstrapCarousel from "../../components/Carousel";
import { Box } from "@mui/system";

export default function Home() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: "100vh",
          width: "100wv",
          display: "flex",
          flexDirection: "column",
          alignContent: "center",
          justifyContent: "center",
        }}
      >
        <Box
          sx={
            {
              // height: "100vh",
              // width: "100wv",
              // display: "flex",
              // flexDirection: "column",
              // alignContent: "center",
              // justifyContent: "center",
            }
          }
        >
          <BootstrapCarousel />
        </Box>
      </Box>
    </>
  );
}
