import { useState } from "react";
import { Box, Typography, Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import ProjectCard from "../../components/ProjectCard";

const projects = [
  {
    id: 1,
    title: "Salut!",
    body: "Salut is an interactive cocktail cabinet and your source for cocktail recipes. Make a catalog or your favorite cocktail recipes. Know what to drink tonight!",
    imageUrl: "/static/images/salut.gif",
    imageUrl2: "/static/images/salut-sc.png",
    link: "https://salut-production.up.railway.app/",
    docs: "https://github.com/kikopocampo/salut",
  },
  {
    id: 2,
    title: "Ranker",
    body: "Ranker is a web application that lets user create polls to be shared with their family, friends, or co-workers. Don't know what movie to watch tonight? Make a poll and send to your friends! Built using Node and Express",
    imageUrl: "/static/images/ranker.gif",
    imageUrl2: "/static/images/ranker-sc.png",
    link: "http://lighthouse-midterm-ranker.herokuapp.com/",
    docs: "https://github.com/kikopocampo/decision-maker",
  },
  {
    id: 3,
    title: "Scheduler",
    body: "Interview Scheduler is a React appllication that lets the host organize and manage interviews in a more efficient manner. It lets users (interviewees) create, edit, and delete their schedule for interviews.",
    imageUrl: "/static/images/scheduler.gif",
    imageUrl2: "/static/images/scheduler-sc.jpeg",
    docs: "https://github.com/kikopocampo/scheduler",
  },
  {
    id: 4,
    title: "Jungle",
    body: "A mini e-commerce application built with Rails 6.1. Jungle, where you can find any plants. Select from our vast selection of plants to take home.",
    imageUrl: "/static/images/jungle.gif",
    imageUrl2: "/static/images/jungle-sc.png",
    docs: "https://github.com/kikopocampo/Jungle",
  },
  {
    id: 5,
    title: "Tiny App",
    body: "TinyApp is a full stack web application built with Node and Express that allows users to shorten long URLs (à la bit.ly). Also includes analytics that shows how many times the link has been visited",
    imageUrl: "/static/images/tinyapp.gif",
    imageUrl2: "/static/images/tinyapp-sc.jpeg",
    docs: "https://github.com/kikopocampo/tinyapp",
  },
];

const Projects = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          zIndex: -1,
          position: "fixed",
          width: "100vw",
          height: "100vh",
        }}
      >
        <Image
          src="/static/images/bg2.jpg"
          alt="background"
          layout="fill"
          objectFit="cover"
        />
      </div>
      <Box
        sx={{
          width: "100vw",
          p: 10,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography className="uppercase text-lg tracking-widest text-gray-500">
          Hover to take a peek
        </Typography>
        <Box
          sx={{
            textAlign: "center",
            m: 4,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {projects.map((item) => {
            return (
              <ProjectCard
                key={item.id}
                imageUrl={item.imageUrl}
                imageUrl2={item.imageUrl2}
                title={item.title}
                body={item.body}
                docs={item.docs}
                link={item.link ? item.link : ""}
              />
            );
          })}
        </Box>
      </Box>
    </>
  );
};

export default Projects;
